# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pricing.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'pricing.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpricing.proto\x12\x05\x62\x65\x62op\"\x8b\x01\n\tLevelInfo\x12\x14\n\x0c\x62\x61se_address\x18\x01 \x01(\x0c\x12\x15\n\rbase_decimals\x18\x02 \x01(\r\x12\x15\n\rquote_address\x18\x03 \x01(\x0c\x12\x16\n\x0equote_decimals\x18\x04 \x01(\r\x12\x10\n\x04\x62ids\x18\x05 \x03(\x01\x42\x02\x10\x01\x12\x10\n\x04\x61sks\x18\x06 \x03(\x01\x42\x02\x10\x01\"C\n\x08LevelMsg\x12 \n\x06levels\x18\x01 \x03(\x0b\x32\x10.bebop.LevelInfo\x12\x15\n\rmaker_address\x18\x02 \x01(\x0c\"c\n\x0cLevelsSchema\x12\x10\n\x08\x63hain_id\x18\x01 \x01(\r\x12\x11\n\tmsg_topic\x18\x02 \x01(\t\x12\x10\n\x08msg_type\x18\x03 \x01(\t\x12\x1c\n\x03msg\x18\x04 \x01(\x0b\x32\x0f.bebop.LevelMsgb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pricing_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LEVELINFO'].fields_by_name['bids']._loaded_options = None
  _globals['_LEVELINFO'].fields_by_name['bids']._serialized_options = b'\020\001'
  _globals['_LEVELINFO'].fields_by_name['asks']._loaded_options = None
  _globals['_LEVELINFO'].fields_by_name['asks']._serialized_options = b'\020\001'
  _globals['_LEVELINFO']._serialized_start=25
  _globals['_LEVELINFO']._serialized_end=164
  _globals['_LEVELMSG']._serialized_start=166
  _globals['_LEVELMSG']._serialized_end=233
  _globals['_LEVELSSCHEMA']._serialized_start=235
  _globals['_LEVELSSCHEMA']._serialized_end=334
# @@protoc_insertion_point(module_scope)
