# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: taker_pricing.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'taker_pricing.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13taker_pricing.proto\x12\x05\x62\x65\x62op\"f\n\x0bPriceUpdate\x12\x0c\n\x04\x62\x61se\x18\x01 \x01(\x0c\x12\r\n\x05quote\x18\x02 \x01(\x0c\x12\x16\n\x0elast_update_ts\x18\x03 \x01(\x04\x12\x10\n\x04\x62ids\x18\x04 \x03(\x01\x42\x02\x10\x01\x12\x10\n\x04\x61sks\x18\x05 \x03(\x01\x42\x02\x10\x01\"7\n\x12\x42\x65\x62opPricingUpdate\x12!\n\x05pairs\x18\x01 \x03(\x0b\x32\x12.bebop.PriceUpdateb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'taker_pricing_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRICEUPDATE'].fields_by_name['bids']._loaded_options = None
  _globals['_PRICEUPDATE'].fields_by_name['bids']._serialized_options = b'\020\001'
  _globals['_PRICEUPDATE'].fields_by_name['asks']._loaded_options = None
  _globals['_PRICEUPDATE'].fields_by_name['asks']._serialized_options = b'\020\001'
  _globals['_PRICEUPDATE']._serialized_start=30
  _globals['_PRICEUPDATE']._serialized_end=132
  _globals['_BEBOPPRICINGUPDATE']._serialized_start=134
  _globals['_BEBOPPRICINGUPDATE']._serialized_end=189
# @@protoc_insertion_point(module_scope)
