from eth_account import Account
from eth_account.messages import encode_typed_data

from greek_mm.bebop.signing import (
    _SINGLE_ORDER_TYPES,
    BEBOP_BLEND_ADDRESS,
    sign_quote,
)

# Well-known anvil/hardhat test key #0 — never used for real funds.
TEST_KEY = "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
TEST_ADDRESS = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"

QUOTE_DATA = {
    "chain_id": 8453,
    "order_signing_type": "SingleOrder",
    "order_type": "Single",
    "onchain_partner_id": 0,
    "expiry": 1750000000,
    "taker_address": "0x1111111111111111111111111111111111111111",
    "maker_address": TEST_ADDRESS,
    "maker_nonce": "12345",
    "receiver": "0x1111111111111111111111111111111111111111",
    "packed_commands": "0",
    "quotes": [
        {
            "taker_token": "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913",
            "maker_token": "0x2222222222222222222222222222222222222222",
            "taker_amount": "105000000",
            "maker_amount": "1000000000000000000",
        }
    ],
}


def test_signature_recovers_to_signer() -> None:
    signed = sign_quote(QUOTE_DATA, TEST_KEY)
    assert signed["sign_scheme"] == "EIP712"

    typed_data = {
        "types": _SINGLE_ORDER_TYPES,
        "primaryType": "SingleOrder",
        "domain": {
            "name": "BebopSettlement",
            "version": "2",
            "chainId": 8453,
            "verifyingContract": BEBOP_BLEND_ADDRESS,
        },
        "message": {
            "partner_id": 0,
            "expiry": 1750000000,
            "taker_address": QUOTE_DATA["taker_address"],
            "maker_address": TEST_ADDRESS,
            "maker_nonce": 12345,
            "taker_token": QUOTE_DATA["quotes"][0]["taker_token"],
            "maker_token": QUOTE_DATA["quotes"][0]["maker_token"],
            "taker_amount": 105000000,
            "maker_amount": 10**18,
            "receiver": QUOTE_DATA["receiver"],
            "packed_commands": 0,
        },
    }
    recovered = Account.recover_message(
        encode_typed_data(full_message=typed_data), signature=signed["signature"]
    )
    assert recovered == TEST_ADDRESS


def test_signature_is_deterministic() -> None:
    a = sign_quote(QUOTE_DATA, TEST_KEY)
    b = sign_quote(QUOTE_DATA, TEST_KEY)
    assert a["signature"] == b["signature"]


# Generated by market-maker/src/bebop/signing.ts (viem signTypedData) for the
# identical QuoteData + key. RFC 6979 deterministic ECDSA means the Python
# signature must match byte-for-byte — this is the node-parity pin.
NODE_SIGNATURE = (
    "0x9fc14b26bb5cb48fef11ccea5c76fefc0a3f0b8b112c619833ad3aabbf5e310e"
    "26e08c57e246c95b716fb617bcb2cb24aa9353ffe11b031acd62ccb47dd68d191c"
)


def test_signature_matches_node_implementation() -> None:
    assert sign_quote(QUOTE_DATA, TEST_KEY)["signature"] == NODE_SIGNATURE


def test_key_without_0x_prefix() -> None:
    with_prefix = sign_quote(QUOTE_DATA, TEST_KEY)
    without_prefix = sign_quote(QUOTE_DATA, TEST_KEY[2:])
    assert with_prefix["signature"] == without_prefix["signature"]


def test_multi_quote_aggregation() -> None:
    # Two partials on the same pair must aggregate amounts before signing.
    data = dict(QUOTE_DATA)
    data["quotes"] = [
        {
            **QUOTE_DATA["quotes"][0],
            "taker_amount": "50000000",
            "maker_amount": "400000000000000000",
        },
        {
            **QUOTE_DATA["quotes"][0],
            "taker_amount": "55000000",
            "maker_amount": "600000000000000000",
        },
    ]
    aggregated = sign_quote(data, TEST_KEY)
    assert aggregated["signature"] == sign_quote(QUOTE_DATA, TEST_KEY)["signature"]
